language: php

sudo: false

php:
  - "5.5"
  - "5.6"
  - "7"
  - "hhvm"

matrix:
  allow_failures:
    - php: "7"
    - php: "hhvm"

before_install:
  - composer self-update
  - pecl install xhprof
  - sh -c 'if [ $(php -r "echo (int) defined(\"HHVM_VERSION\");") -eq 0 ]; then pecl install channel://pecl.php.net/xhprof-0.9.3; fi'

install: composer install

script: ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script: ./vendor/bin/coveralls
